/*
* webrtcfy.js
* requires peerjs (http://peerjs.com/) for establishing the peer connection
*
* wrapper for creating and handling webrtc connections
* triggers events upon significant events
*
* @author Jarón Barends
*
*/

;(function($) {

	'use strict';

	//define semi-global (within this anonymous function's scope) variables, prefix with sg
	var sgPluginname = 'webrtcfy',
		sgPeerJSApiKey = 'a7f838qn54eljtt9',
		sgPeerWrapper = {
			id: '',//the id of this instance's peer connection (it is also present in this object's peer-property, but we need it very often)
			peer: {},//peer object generated by peer.js
			connections: [],
			sendData: function(){}
		};//communications object, reference to this object can be passed around to other add-ons
	


	/*-- Start peer and connection functions --*/


		/**
		* send data to one or more data connections; this function will be made available to add-ons
		* through the sgPeerWrapper object
		* @param {object} data The data to be sent
		* @param {DataConnection} conn [optional] The connection to send the message to; when conn is not provided, send to all connections
		* @returns {undefined}
		*/
		var sendData = function(data, conn) {
			if (conn) {
				conn.send(data);
			} else {
				for (var i=0, len = sgPeerWrapper.connections.length; i<len; i++) {
					conn = sgPeerWrapper.connections[i];
					conn.send(data);
				}
			}
		};


		/**
		* Create peerWrapper object that can be passed around to other plugins
		* This object will handle communication between this window and peer-windows
		* @returns {undefined}
		*/
		var initPeerWrapper = function() {

			sgPeerWrapper.sendData = sendData;
			sgPeerWrapper.triggerEvent = triggerEvent;

			//create a jspeer peer-object
			sgPeerWrapper.peer = new Peer({key: sgPeerJSApiKey});

			sgPeerWrapper.peer.on('open', function(id) {
				//a peer has been created by peerjs; it has been assigned an id which is passed into this function
				sgPeerWrapper.id = id;
				//send an event to any listening other scripts to tell this peerWrapper is ready
				triggerEvent('peerready', {peer:sgPeerWrapper});

				addEventListeners();
				initConnectionForm();//todo: this should not be in this file :)

			});

			//handle incomming connections
			sgPeerWrapper.peer.on('connection', checkConnection);

		};


		/**
		* 
		* @param {misc} data Data object
		* @param {DataConnection object} conn DataConnection that sent the data
		* @returns {undefined}
		*/
		var dataHandler = function(data, conn) {
			var type = data.type;

			switch(type) {
			}

		};
		
		
		/**
		* handle closing a peer connection 
		* @param {string} varname Description
		* @returns {undefined}
		*/
		var connectionClosedHandler = function(conn) {
			//removeDisplayedConnection(conn);
		};
		

		/**
		* Initialize a connection with a peer
		* @param {DataConnection object} conn DataConnection object for the connection with this peer (every peer has its own DataConnection object)
		* @returns {undefined}
		*/
		var initConnection = function(conn) {
			sgPeerWrapper.connections.push(conn);

			//when data is received from a peer
			conn.on('data', function(data) {
				dataHandler(data, conn);
			});

			//when a connection is closed
			conn.on('close', function() {connectionClosedHandler(conn);});

			//send event to let other scripts know a connection is ready
			//somehow, we can't send data immediately, even if conn is open?
			setTimeout(function() {
				var data = {
					connection: conn
				};
				triggerEvent('connectionready', data);
			});

		};



		/**
		* check if a new connection is open and ready
		* @param {object} conn The jspeer-connection-object to check
		* @returns {undefined}
		*/
		var checkConnection = function(conn) {
			if (conn.open) {
				initConnection(conn);
			} else {
				setTimeout(function() {
					checkConnection(conn);
				}, 100);
			}
		};


		/**
		* start Connection with another peer
		* @param {string} peerId Id of the peer to start a connection with
		* @returns {undefined}
		*/
		var startConnection = function(peerId) {
			var userObject = getUserObject(),
				options = {
					metadata: {
						users: [userObject]
					}
				},
				conn = sgPeerWrapper.peer.connect(peerId, options);//returns DataConnection object
				//todo: what's the use of this options object?
			
			checkConnection(conn);
		};


		/**
		* initialize the form to create a connection
		* @returns {undefined}
		* @todo This should be put into its own separate file
		*/
		var initConnectionForm = function() {
			var id = sgPeerWrapper.id,
				href = document.location.href + '?peerId='+id;

			$('#yourConnectionId').val(id);
			$('#url-to-this-window').val(href);

			$('#yourConnectionId, #url-to-this-window').on('click', function(e) {
				e.currentTarget.select();
			});

			checkPeerIdInUrl();

			$('#connectionForm').on('submit', function(e) {
				e.preventDefault();
				var peerConnectionId = $('#peerConnectionId').val();
				startConnection(peerConnectionId);
			});
		};


		/**
		* handle request to close a connection
		* peerjs will let the connection send a close event when the connection is closed
		* @param {peerjs DataConnection} conn The data connection to remove
		* @returns {undefined}
		*/
		var closeConnectionHandler = function(e, conn) {
			conn.close();
		};
		


		/**
		* addEventListeners
		* these events may also be triggered by other scripts to which this script's peer-object is passed
		* @param {string} varname Description
		* @returns {undefined}
		*/
		var addEventListeners = function() {
			//listen for requests to close a connection
			$(document).on('closeConnection.'+sgPluginname, closeConnectionHandler);
		};
		


	/*-- End peer and connection functions --*/



	/*-- Start event sending functions --*/


		/**
		* send an event
		* @param {string} eventName The name of the event to send; pluginname will be added
		* @param {object} data [optional] Data to send along with the event
		* @returns {undefined}
		*/
		var triggerEvent = function(eventName, data) {
			eventName += '.'+sgPluginname;
			$(document).trigger(eventName, data);
		};
		

	/*-- End event sending functions --*/

	

	/*-- Start general functions --*/


		/**
		* get an element from a cloneSrc
		* @param {string of jQuery object} selector The selector for the cloneSrc, or the sloneSrc element itself
		* @returns {jQuery object} The cloned element
		*/
		var getClone = function(selector) {
			var $clone;
			if (typeof selector === 'string') {
				$clone = $(selector).clone();
			} else {
				$clone = selector.clone();
			}
			$clone.removeClass('cloneSrc');

			return $clone;
		};


		/**
		* get an object containing user data
		* @returns {object} object containing peer id and name
		*/
		var getUserObject = function() {
			var userObject = {
				peer: sgPeerWrapper.id,
				name: $('#nickname').val()
			};

			return userObject;
		};


		/**
		* check if the current url contains a peer id
		* @returns {undefined}
		*/
		var checkPeerIdInUrl = function() {
			var href = document.location.href,
				peerIdx = href.indexOf('?peerId'),
				peerId;

			if (peerIdx !== -1) {
				peerId = href.substr((peerIdx+8));
				$('#peerConnectionId').val(peerId);
				//TO DO: create connection automatically?
			}
		};
		


	/*-- End general functions --*/
	


	/**
	* initialize all
	* @param {string} varname Description
	* @returns {undefined}
	*/
	var init = function() {
		initPeerWrapper();
	};


	$(document).ready(init);
	
	
})(jQuery);